name: compphysiol CI
on: 
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  test:
    name: Run MATLAB Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          release: R2023b
      - name: Run code checks and tests using buildtool
        uses: matlab-actions/run-build@v2
      - name: Upload code coverage report to Codecov
        uses: codecov/codecov-action@v4
        if: always()
        with:
          files: reports/codecoverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: niklhart/compphysiol